//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSmsLog
    {
        public int process_id { get; set; }
        public bool sms_status { get; set; }
        public Nullable<System.DateTime> sms_time { get; set; }
        public long token_id { get; set; }
    }
}
