//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceDetail
    {
        public long service_id { get; set; }
        public long token_id { get; set; }
        public long customer_id { get; set; }
        public string issues { get; set; }
        public string solutions { get; set; }
        public System.DateTime service_datetime { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public int service_sub_type_id { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblTokenQueue tblTokenQueue { get; set; }
        public virtual tblServiceSubType tblServiceSubType { get; set; }
    }
}
