//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTokenQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTokenQueue()
        {
            this.tblServiceDetails = new HashSet<tblServiceDetail>();
        }
    
        public long token_id { get; set; }
        public int branch_id { get; set; }
        public int service_type_id { get; set; }
        public string contact_no { get; set; }
        public int token_no { get; set; }
        public System.DateTime service_date { get; set; }
        public short service_status_id { get; set; }
        public Nullable<int> counter_id { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> cancel_time { get; set; }
        public Nullable<System.DateTime> CallTime { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblCounter tblCounter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblServiceDetail> tblServiceDetails { get; set; }
        public virtual tblServiceStatu tblServiceStatu { get; set; }
        public virtual tblServiceType tblServiceType { get; set; }
    }
}
